//! Source-derived SSC generation and signature-generic binding semantics.

use gandr_theory_levitation::Attrs;
use gandr_theory_levitation::BridgeArity;
use gandr_theory_levitation::DeclPolarity;
use gandr_theory_levitation::FreeTerm;
use gandr_theory_levitation::Name;
use gandr_theory_levitation::NominalId;
use gandr_theory_levitation::NominalSerial;
use gandr_theory_levitation::OperDesc;
use gandr_theory_levitation::Representability;
use gandr_theory_levitation::SignDesc;
use gandr_theory_levitation::SortDesc;
use gandr_theory_levitation::SortIndex;
use gandr_theory_levitation::SortRef;
use gandr_theory_levitation::TranslationError;
use gandr_theory_levitation::WfKind;
use gandr_theory_levitation::check_desc;
use gandr_theory_levitation::first_order;
use gandr_theory_levitation::serialize_desc;

/// A single-output operation fixture.
///
/// # Specification
/// trivial.
fn op(
    name: impl Into<Name>,
    inputs: Vec<SortRef>,
    output: SortRef,
) -> OperDesc
{
    OperDesc::new(
        name,
        BridgeArity::single_output(inputs, output),
        Attrs::empty(),
    )
}

/// A signature fixture with no equations beyond those generated by SSC.
///
/// # Specification
/// trivial.
fn signature(
    name: impl Into<Name>,
    sorts: Vec<SortDesc>,
    operations: Vec<OperDesc>,
) -> SignDesc<()>
{
    SignDesc::new(
        NominalId::new(NominalSerial::from(0_u64), name),
        [],
        [],
        operations,
        [],
        DeclPolarity::Data,
        Attrs::empty(),
    )
    .with_sorts(sorts)
}

/// The binding and application signature of pure lambda syntax.
///
/// # Specification
/// trivial.
fn lc() -> SignDesc<()>
{
    signature(
        "LC",
        vec![SortDesc::new("Tm", DeclPolarity::Data).representable()],
        vec![
            op(
                "lam",
                vec![SortRef::new("t", "Tm").pi_plus([SortIndex::new("x", "Tm")])],
                SortRef::new("", "Tm"),
            ),
            op(
                "app",
                vec![SortRef::new("t", "Tm"), SortRef::new("u", "Tm")],
                SortRef::new("", "Tm"),
            ),
        ],
    )
}

/// The identity-return signature, including its type indices.
///
/// # Specification
/// trivial.
fn identity_return() -> SignDesc<()>
{
    let a = FreeTerm::var("A");
    let b = FreeTerm::var("B");
    signature(
        "IdentityReturn",
        vec![
            SortDesc::new("VTy", DeclPolarity::Data),
            SortDesc::new("CTy", DeclPolarity::Data),
            SortDesc::family("VTm", DeclPolarity::Data, [SortIndex::new("A", "VTy")])
                .representable(),
            SortDesc::family("CTm", DeclPolarity::Data, [SortIndex::new("B", "CTy")]),
        ],
        vec![
            op("F", vec![SortRef::new("A", "VTy")], SortRef::new("", "CTy")),
            op(
                "Arrow",
                vec![SortRef::new("A", "VTy"), SortRef::new("B", "CTy")],
                SortRef::new("", "CTy"),
            ),
            op(
                "ret",
                vec![
                    SortRef::new("A", "VTy"),
                    SortRef::new("t", "VTm").applied([a.clone()]),
                ],
                SortRef::new("", "CTm").applied([FreeTerm::op("F", [a.clone()])]),
            ),
            op(
                "lam",
                vec![
                    SortRef::new("A", "VTy"),
                    SortRef::new("B", "CTy"),
                    SortRef::new("t", "CTm")
                        .applied([b.clone()])
                        .pi_plus([SortIndex::new("x", "VTm").applied([a.clone()])]),
                ],
                SortRef::new("", "CTm").applied([FreeTerm::op("Arrow", [a, b])]),
            ),
        ],
    )
}

#[test]
fn restricted_binding_requires_representability()
{
    let mut source = lc();
    assert_eq!(check_desc(&source), []);
    assert!(
        serialize_desc(&source)
            .as_ref()
            .contains("pi+ (x : Tm) . Tm")
    );
    source.sorts[0].representability = Representability::Ordinary;
    let diagnostics = check_desc(&source);
    assert_eq!(
        diagnostics
            .iter()
            .map(|diagnostic| diagnostic.kind)
            .collect::<Vec<_>>(),
        [WfKind::NonRepresentableBinder]
    );
    source.opers[0].arity.inputs[0].bindings[0].sort = Name::from("Absent");
    assert_eq!(check_desc(&source)[0].kind, WfKind::NonRepresentableBinder);
}

#[test]
fn generation_matches_derived_lc()
{
    // Derivation: Definition 4 minus category/functoriality equations, replace
    // pairing by single and lift (§7); the four index laws are over the empty
    // index telescope, hence disappear. Naturality retains app and lifts lam.
    // Beta belongs to the source theory, not its binding signature; this
    // experiment adds only SSC equations and operation naturality.
    let expected = r#"sign LC$ssc {
        sort $Con : Type;
        sort $Sub(D : $Con, G : $Con) : Type;
        sort Tm(G : $Con) : Type;
        oper $empty : () --> $Con;
        oper $sub_Tm : (G : $Con, D : $Con, t : Tm(G), s : $Sub(D, G)) --> Tm(D);
        oper $extend_Tm : (G : $Con) --> $Con;
        oper $p_Tm : (G : $Con) --> $Sub($extend_Tm(G), G);
        oper $q_Tm : (G : $Con) --> Tm($extend_Tm(G));
        oper $single_Tm : (G : $Con, a : Tm(G)) --> $Sub(G, $extend_Tm(G));
        oper $lift_Tm : (G : $Con, D : $Con, s : $Sub(D, G)) --> $Sub($extend_Tm(D), $extend_Tm(G));
        oper lam : (G : $Con, t : Tm($extend_Tm(G))) --> Tm(G);
        oper app : (G : $Con, t : Tm(G), u : Tm(G)) --> Tm(G);
        rule $sub_Tm($q_Tm, $single_Tm(b)) ==> b;
        rule $sub_Tm($q_Tm, $lift_Tm(s)) ==> $q_Tm;
        rule $sub_Tm($sub_Tm(b, $p_Tm), $lift_Tm(s)) ==> $sub_Tm($sub_Tm(b, s), $p_Tm);
        rule $sub_Tm($sub_Tm(b, $p_Tm), $single_Tm(a)) ==> b;
        rule $sub_Tm(lam(t), s) ==> lam($sub_Tm(t, $lift_Tm(s)));
        rule $sub_Tm(app(t, u), s) ==> app($sub_Tm(t, s), $sub_Tm(u, s)); }"#;
    let model = first_order(&lc()).expect("LC is a finitary signature");
    assert_eq!(
        serialize_desc(&model).as_ref(),
        expected.split_whitespace().collect::<Vec<_>>().join(" ")
    );
    assert_eq!(check_desc(&model), []);
}

#[test]
fn eight_dependent_single_substitution_laws()
{
    let source = signature(
        "Dependent",
        vec![
            SortDesc::new("Ty", DeclPolarity::Data),
            SortDesc::family("Tm", DeclPolarity::Data, [SortIndex::new("A", "Ty")]).representable(),
        ],
        vec![],
    );
    let model = first_order(&source).expect("dependent family translates");
    let equations: Vec<String> = model
        .rules
        .iter()
        .map(|rule| format!("{} = {}", rule.lhs, rule.rhs))
        .collect();
    assert_eq!(equations, [
        "$sub_Tm($q_Tm, $single_Tm(b)) = b",
        "$sub_Tm($q_Tm, $lift_Tm(s)) = $q_Tm",
        "$sub_Tm($sub_Tm(b, $p_Tm), $lift_Tm(s)) = $sub_Tm($sub_Tm(b, s), $p_Tm)",
        "$sub_Tm($sub_Tm(b, $p_Tm), $single_Tm(a)) = b",
        "$sub_Ty($sub_Ty(A, $p_Tm), $lift_Tm(s)) = $sub_Ty($sub_Ty(A, s), $p_Tm)",
        "$sub_Ty($sub_Ty(A, $p_Tm), $single_Tm(b)) = A",
        "$sub_Ty($sub_Ty(A, $single_Tm(b)), s) = $sub_Ty($sub_Ty(A, $lift_Tm(s)), $single_Tm($sub_Tm(b, s)))",
        "$sub_Ty($sub_Ty(A, $lift_Tm($p_Tm)), $single_Tm($q_Tm)) = A",
    ]);
    assert_eq!(check_desc(&model), []);
}

#[test]
fn indexed_signature_translates_without_name_cases()
{
    let model = first_order(&identity_return()).expect("identity-return translates");
    assert_eq!(check_desc(&model), []);
    let lam = model
        .opers
        .iter()
        .find(|operation| operation.name.as_ref() == "lam")
        .expect("lambda operation");
    let body = &lam.arity.inputs[3];
    assert_eq!(
        body.arguments
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>(),
        [
            "$extend_VTm(G, A)",
            "$sub_CTy(G, $extend_VTm(G, A), B, $p_VTm(G, A))",
        ]
    );
    assert!(body.bindings.is_empty());
    assert!(
        !model
            .opers
            .iter()
            .any(|operation| operation.name.as_ref() == "$q_CTm")
    );
    let renamed = signature(
        "Renamed",
        vec![SortDesc::new("Expression", DeclPolarity::Data).representable()],
        vec![op(
            "abstract",
            vec![SortRef::new("body", "Expression").pi_plus([
                SortIndex::new("outer", "Expression"),
                SortIndex::new("inner", "Expression"),
            ])],
            SortRef::new("", "Expression"),
        )],
    );
    let renamed = first_order(&renamed).expect("names do not select translation cases");
    assert_eq!(
        renamed.rules.last().expect("naturality").rhs.to_string(),
        "abstract($sub_Expression(body, $lift_Expression($lift_Expression(s))))"
    );
}

#[test]
fn translation_refuses_non_signatures()
{
    let mut source = lc();
    source.sorts[0].representability = Representability::Ordinary;
    assert!(matches!(
        first_order(&source),
        Err(TranslationError::Malformed(_))
    ));
    let reserved = signature(
        "Reserved",
        vec![SortDesc::new("$Con", DeclPolarity::Data)],
        vec![],
    );
    assert_eq!(
        first_order(&reserved),
        Err(TranslationError::ReservedName(Name::from("$Con")))
    );
    let unknown = signature(
        "Unknown",
        vec![SortDesc::family("Tm", DeclPolarity::Data, [
            SortIndex::new("A", "Missing"),
        ])],
        vec![],
    );
    assert_eq!(
        first_order(&unknown),
        Err(TranslationError::UnknownIndexSort(Name::from("Missing")))
    );
    let mut product = lc();
    product.opers[0].arity.outputs = Box::default();
    assert!(matches!(
        first_order(&product),
        Err(TranslationError::Malformed(_))
    ));
    let mut product = lc();
    product.opers[0].arity.factors = Box::from([0_u32]);
    product.opers[0].arity.source = Box::default();
    assert_eq!(
        first_order(&product),
        Err(TranslationError::NonProductOperation(Name::from("lam")))
    );
}

#[path = "glf/model.rs"]
mod model;
